# Workflow to run unit tests on the source
name: Unit Testing

# When will this workflow run?
on:
  # run on every push to main, i.e. PR merges
  push:
    branches: [ "main" ]

  # Triggers the workflow on pushes to open pull requests with code changes
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/unit-tests.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# No permissions required to run this code
permissions: {}

jobs:
  unit-test:
    name: Build & test (${{ matrix.python-version }} | ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      # continue testing other configurations even if a matrix job fails
      fail-fast: false
      matrix:
        # Supported Python versions on Linux Ubuntu
        os: ["ubuntu-latest"]
        python-version: ["3.13", "3.12", "3.11", "3.10"]
        # test latest python version on macOS
        include:
        - os: macos-latest
          python-version: "3.13"

    steps:
    # Checks-out repository under $GITHUB_WORKSPACE, so job can access it
    - name: Checkout code
      with:
        persist-credentials: false
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
  
    - name: Install Package and Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv tctrack_venv
        . tctrack_venv/bin/activate
        pip install .[test]

    - name: Run unit tests
      if: always()
      run: |
        cd ${{ github.workspace }}
        . tctrack_venv/bin/activate
        pytest tests/unit
